### ISSUE TITLE
License terms with respect to a PDF file produced with the cam-thesis template

### ISSUE THREAD

**Issue by kwitaszczyk** [cambridge/thesis#73]
The current license states that "Redistributions in binary form must reproduce the above copyright notice". Based on that, one could state that a distributed PDF file, as a binary form of distribution of the cam-thesis template, should include the copyright notice and acknowledge the use of the cam-thesis repository.

Could you tell how the cam-thesis license relates to PDF files produced with the help of the cam-thesis repository? If you expect such files to include the copyright notice, what would be your recommended way to do so?

Thank you for maintaining this repository.

**Comment by mgkuhn** [comment]
I would argue that a PDF produced with the help of a LaTeX package counts as *data output* from executing the macros in the class file, and not as a compiled *binary* translation of the class file. The instructions found in [cam-thesis.cls](https://github.com/cambridge/thesis/blob/master/cam-thesis.cls) are not translated/compiled into instructions found in the PDF. Instead they are executed, and the PDF is the resulting data produced.

Therefore, I don't think the PDF needs to include a copyright notice for this LaTeX package.

Having said that, I note that most LaTeX packages use the [LPPL](https://www.latex-project.org/lppl/) instead, which doesn't mention any “binary”. Perhaps that might be a more useful licence?

I also note that the `License` file currently does not specify to which files in the repository it applies. This might be problematic because of the many third-party files collected under `CollegeShields/`.

**Comment by kwitaszczyk** [comment]
This clarifies the case for me. Thank you. A troubleshooting entry with this question in README.md might be useful for others in the future, but that can be discussed separately in a pull request.

This issue can be closed now but I will leave it open since Markus mentioned two other suggestions to the maintainers.
