### ISSUE TITLE
How can I add roman numeral page numbering before Chapter 1

### ISSUE THREAD

**Issue by PugseV** [cambridge/thesis#75]
I would like to have the the abstract, table of contents, list of figures, etc... have numbering i, ii, iii, iv, etc... so that chapter 1 begins on page 1. Currently the declaration, abstract, acknowledgements, and table of contents have no page numbers, but the list of figures (on the next page) starts at pg 13.

Apologies in advance if this is trivial - I am not the best at latex.

**Comment by mgkuhn** [comment]
To use a separate Roman-numeral page-number sequence for pre-matter in your book, you'd have to change from the `report` class to the `book` class.

Note, however, that we specifically recommend *not* to do this for a PhD thesis that will likely mainly be mostly read as a PDF. This is because otherwise you'll get in PDF viewers *two* sets of page numbers displayed, and there will then be confusion as to which is meant if someone refers to a page number. Specifically, if you submit your thesis as a tech-report, [we will ask you](https://www.cl.cam.ac.uk/techreports/submission.html#pageno) to use just a single sequence of Arabic numbers, how `report.cls` does it.

You could try to change in
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%
%% Using report class as base.
%%
%%%%%
\PassOptionsToClass{a4paper,12pt,twoside,openright}{report}
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{report}}
\ProcessOptions\relax
\LoadClass{report}
```

all occurrences of `report` with `book`.
